export const routes = {
  firstPage: "/",
  loginPage: "/login",
  adminSchoolPage: "/admin/school",
  adminEditSchoolPage: "/admin/school/edit",
  adminClassesPage: "/admin/classes",
  adminTeachersPage: "/admin/teachers",
  adminStudentsPage: "/admin/students",
  adminClassPage: "/admin/classes/:id",
  adminSubjectsPage: "/admin/subjects",
  adminCallSchedulePage: "/admin/schedule",
  adminEditCallSchedulePage: "/admin/schedule/edit",
  adminClassSubjectsPage: "/admin/classes/:id/subject",
  adminClassSchedulePage: "/admin/classes/:id/schedule",
  adminEditClassSchedulePage: "/admin/classes/:id/schedule/edit",
  adminClassJournalsPage: "/admin/classes/:id/journals",
  adminClassJournalPage: "/admin/classes/:id/journals/:journalId",

  teacherSchoolPage: "/teacher/school",
  teacherMyClassesPage: "/teacher/my_classes",
};
