export const routes = {
  firstPage: "/",
  loginPage: "/login",
  schoolPage: "/school",
  editSchoolPage: "/school/edit",
  classesPage: "/classes",
  teachersPage: "/teachers",
  studentsPage: "/students",
  classPage: "/classes/:id",
  subjectsPage: "/subjects",
  callSchedulePage: "/schedule",
  editCallSchedulePage: "/schedule/edit",
  classSubjectsPage: "/classes/:id/subject",
  classSchedulePage: "/classes/:id/schedule",
  editClassSchedulePage: "/classes/:id/schedule/edit",
  classJournalsPage: "/classes/:id/journals",
  classJournalPage: "/classes/:id/journals/:journalId",
  journalsPage: "/journals",
  journalPage: "/journals/:id",
};
